
name: Unit tests for backend API

on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch as it
  # has the codebase for backend API management
  push:
    branches: [ "update-ui" ]
  pull_request:
    branches: [ "update-ui" ]
    
jobs:
  # This workflow contains a single job called "test"
 test:
    # The type of runner that the job will run on all the OSes
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #Install fakeindexed-db
      - name: Install fakeindexed-db
        run: npm install --save-dev fake-indexeddb

      #Install jest
      - name: Jest for Unit testing 
        run: npm install --save-dev jest
      
      #Run the unit tests
      - name: Backend Unit Tests
        run: npx jest --runInBand db.test.js
